// Mock data for the prototype. Every name here is fictional — no real patients.
// DataContext serves these whenever Supabase isn't configured or comes back empty.
//
// TODO(Phase 10): replace with the seed script once the services own this data.

import type {
  AdmissionTrendPoint,
  InventoryItem,
  LabTest,
  Patient,
  RevenuePoint,
  Ward,
} from "./types";

// ─── CHARTS ───

export const REVENUE_DATA: RevenuePoint[] = [
  { day: "Mon", revenue: 186400 },
  { day: "Tue", revenue: 204900 },
  { day: "Wed", revenue: 198300 },
  { day: "Thu", revenue: 221750 },
  { day: "Fri", revenue: 242500 },
  { day: "Sat", revenue: 168200 },
  { day: "Sun", revenue: 142600 },
];

export const ADMISSION_TRENDS: AdmissionTrendPoint[] = [
  { month: "Jan", admissions: 312, discharges: 298 },
  { month: "Feb", admissions: 287, discharges: 280 },
  { month: "Mar", admissions: 341, discharges: 322 },
  { month: "Apr", admissions: 356, discharges: 349 },
  { month: "May", admissions: 398, discharges: 371 },
  { month: "Jun", admissions: 422, discharges: 405 },
];

// ─── PATIENTS ───

export const PATIENTS: Patient[] = [
  {
    id: "MPI-2026-00118",
    name: "Juan Dela Cruz",
    age: 64,
    gender: "M",
    department: "ICU",
    ward: "ICU",
    bed: "ICU-03",
    diagnosis: "Community-acquired pneumonia, high risk",
    icd10: "J18.9",
    status: "Critical",
    mews: 7,
    admittedAt: "2026-09-21T08:40:00+08:00",
  },
  {
    id: "MPI-2026-00124",
    name: "Maria Clara Santos",
    age: 29,
    gender: "F",
    department: "OB-Gyne",
    ward: "OB-Gyne Ward",
    bed: "OB-05",
    diagnosis: "Pre-eclampsia",
    icd10: "O14.9",
    status: "Stable",
    mews: 2,
    admittedAt: "2026-09-23T14:15:00+08:00",
  },
  {
    id: "MPI-2026-00131",
    name: "Roberto Villanueva",
    age: 52,
    gender: "M",
    department: "Surgical Ward",
    ward: "Surgical Ward",
    bed: "SW-02",
    diagnosis: "Acute appendicitis, post-appendectomy",
    icd10: "K35.8",
    status: "Recovering",
    mews: 3,
    admittedAt: "2026-09-22T22:05:00+08:00",
  },
  {
    id: "MPI-2026-00135",
    name: "Ana Liza Reyes",
    age: 41,
    gender: "F",
    department: "Medical Ward",
    ward: "Medical Ward A",
    bed: "MA-07",
    diagnosis: "Dengue fever with warning signs",
    icd10: "A97.1",
    status: "Stable",
    mews: 4,
    admittedAt: "2026-09-24T09:30:00+08:00",
  },
  {
    id: "MPI-2026-00139",
    name: "Kristine Mae Bautista",
    age: 8,
    gender: "F",
    department: "Pediatrics",
    ward: "Pediatrics Ward",
    bed: "PD-01",
    diagnosis: "Acute gastroenteritis with moderate dehydration",
    icd10: "A09",
    status: "Recovering",
    mews: 1,
    admittedAt: "2026-09-24T16:50:00+08:00",
  },
  {
    id: "MPI-2026-00142",
    name: "Ernesto Manalo",
    age: 71,
    gender: "M",
    department: "ICU",
    ward: "ICU",
    bed: "ICU-06",
    diagnosis: "Acute myocardial infarction",
    icd10: "I21.9",
    status: "Critical",
    mews: 6,
    admittedAt: "2026-09-25T02:10:00+08:00",
  },
  {
    id: "MPI-2026-00147",
    name: "Josefina Aquino",
    age: 58,
    gender: "F",
    department: "Medical Ward",
    ward: "Medical Ward B",
    bed: "MB-04",
    diagnosis: "Type 2 diabetes mellitus with hyperglycemia",
    icd10: "E11.65",
    status: "Stable",
    mews: 2,
    admittedAt: "2026-09-23T11:00:00+08:00",
  },
  {
    id: "MPI-2026-00150",
    name: "Mark Anthony Garcia",
    age: 23,
    gender: "M",
    department: "ER",
    ward: "ER Holding",
    bed: "ER-02",
    diagnosis: "Closed fracture of the left radius",
    icd10: "S52.5",
    status: "Stable",
    mews: 1,
    admittedAt: "2026-09-25T07:45:00+08:00",
  },
  {
    id: "MPI-2026-00153",
    name: "Lourdes Pascual",
    age: 66,
    gender: "F",
    department: "Medical Ward",
    ward: "Isolation Ward",
    bed: "IS-02",
    diagnosis: "Pulmonary tuberculosis",
    icd10: "A15.0",
    status: "Recovering",
    mews: 3,
    admittedAt: "2026-09-19T13:20:00+08:00",
  },
  {
    id: "MPI-2026-00109",
    name: "Ramon Castillo",
    age: 47,
    gender: "M",
    department: "Surgical Ward",
    ward: "Surgical Ward",
    bed: "—",
    diagnosis: "Cholelithiasis, post-cholecystectomy",
    icd10: "K80.2",
    status: "Discharged",
    mews: 0,
    admittedAt: "2026-09-16T10:00:00+08:00",
  },
];

// ─── INVENTORY ───

// "status" is stored rather than derived so the table can show a manual
// override (e.g. a recall) without us re-deriving it from quantity/capacity.
export const INVENTORY: InventoryItem[] = [
  {
    id: "INV-MED-001",
    name: "Paracetamol 500 mg tablet",
    category: "Medication",
    quantity: 4200,
    capacity: 5000,
    unit: "tabs",
    status: "Good",
    expiry: "2027-08-31",
  },
  {
    id: "INV-MED-014",
    name: "Ceftriaxone 1 g vial",
    category: "Medication",
    quantity: 38,
    capacity: 400,
    unit: "vials",
    status: "Critical",
    expiry: "2026-12-15",
  },
  {
    id: "INV-MED-022",
    name: "Oral rehydration salts sachet",
    category: "Medication",
    quantity: 260,
    capacity: 1000,
    unit: "sachets",
    status: "Low",
    expiry: "2027-03-01",
  },
  {
    id: "INV-EQP-003",
    name: "Pulse oximeter",
    category: "Equipment",
    quantity: 22,
    capacity: 30,
    unit: "units",
    status: "Good",
    expiry: null,
  },
  {
    id: "INV-SUR-009",
    name: "Sterile surgical gloves (size 7)",
    category: "Surgical",
    quantity: 140,
    capacity: 600,
    unit: "pairs",
    status: "Low",
    expiry: "2026-11-30",
  },
  {
    id: "INV-LAB-004",
    name: "CBC reagent kit",
    category: "Laboratory",
    quantity: 9,
    capacity: 60,
    unit: "kits",
    status: "Critical",
    expiry: "2026-10-20",
  },
];

// ─── WARDS ───

// 7 wards × 10 beds = 70 total, 47 occupied — matches the Bed Management stats
export const WARDS: Ward[] = [
  { id: "W-MA", name: "Medical Ward A", floor: "2F", totalBeds: 10, occupied: 8 },
  { id: "W-MB", name: "Medical Ward B", floor: "2F", totalBeds: 10, occupied: 7 },
  { id: "W-SW", name: "Surgical Ward", floor: "3F", totalBeds: 10, occupied: 6 },
  { id: "W-PD", name: "Pediatrics Ward", floor: "3F", totalBeds: 10, occupied: 4 },
  { id: "W-OB", name: "OB-Gyne Ward", floor: "4F", totalBeds: 10, occupied: 7 },
  { id: "W-ICU", name: "ICU", floor: "1F", totalBeds: 10, occupied: 9 },
  { id: "W-IS", name: "Isolation Ward", floor: "1F", totalBeds: 10, occupied: 6 },
];

// ─── LAB & RADIOLOGY ───

export const LAB_TESTS: LabTest[] = [
  {
    id: "LAB-2026-0412",
    patientId: "MPI-2026-00118",
    patientName: "Juan Dela Cruz",
    test: "Arterial blood gas",
    kind: "Laboratory",
    priority: "Urgent",
    status: "Pending",
    requestedAt: "2026-09-25T06:20:00+08:00",
  },
  {
    id: "LAB-2026-0415",
    patientId: "MPI-2026-00135",
    patientName: "Ana Liza Reyes",
    test: "Complete blood count with platelet",
    kind: "Laboratory",
    priority: "Urgent",
    status: "In Progress",
    requestedAt: "2026-09-25T07:05:00+08:00",
  },
  {
    id: "RAD-2026-0088",
    patientId: "MPI-2026-00150",
    patientName: "Mark Anthony Garcia",
    test: "X-ray, left forearm AP/lateral",
    kind: "Radiology",
    priority: "Routine",
    status: "Completed",
    requestedAt: "2026-09-25T08:00:00+08:00",
  },
  {
    id: "LAB-2026-0419",
    patientId: "MPI-2026-00147",
    patientName: "Josefina Aquino",
    test: "HbA1c",
    kind: "Laboratory",
    priority: "Routine",
    status: "Pending",
    requestedAt: "2026-09-25T08:30:00+08:00",
  },
  {
    id: "RAD-2026-0091",
    patientId: "MPI-2026-00153",
    patientName: "Lourdes Pascual",
    test: "Chest X-ray PA",
    kind: "Radiology",
    priority: "Routine",
    status: "Pending",
    requestedAt: "2026-09-25T09:10:00+08:00",
  },
];
